version: '3'

volumes:
  db_data:

services:

  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: "mysql -uroot -pexample -e \"show databases;\""

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./shared_drive:/mnt/shared_drive
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
